version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DEBUG=False
      - OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxxx
#      - DB_URL=postgres://postgres:postgrespw@localhost:49153/chatgpt
    volumes:
      - static_volume:/app/static
    ports:
      - '8000:8000'
    networks:
        - chatgpt_network
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - static_volume:/app/static
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - chatgpt_network

networks:
  chatgpt_network:
      driver: bridge

volumes:
  static_volume: